aerogear/offix

README.md
docs/index.md
docs/sections/ref-offline.md

fix: documentation updates for offline workflow

---

packages/offix-client/src/cache/IDProcessor.ts
packages/offix-client/src/conflicts/ConflictProcesor.ts
packages/offix-client/src/links/LinksBuilder.ts
packages/offix-client/src/offline/OfflineLink.ts
packages/offix-client/src/offline/OfflineQueue.ts
packages/offix-client/src/offline/procesors/IResultProcessor.ts

Offline processors give the ability to inject behavior for offline queue and have different procesor modules altogether - cache, conflicts and offline.

fix: Offline processors

---

docs/getting-started.md
docs/index.md
docs/sections/ref-advanced.md
docs/sections/ref-conflict-client.md
docs/sections/ref-offline.md

docs: update site to include offline mutate

---

package.json
packages/offix-client/src/offline/procesors/IDProcessor.ts
packages/offix-client/test/IdProcesorTest.ts

fix for https://github.com/aerogear/offix/issues/74
Waiting for more info to write integration tests.

fix: Refactor id processor to always use toString

---

docs/ref-cache.md
docs/ref-release-notes.md
packages/offix-cache/src/cache/CacheUpdates.ts
packages/offix-cache/src/cache/mutations.ts
packages/offix-cache/src/cache/subscriptions.ts
packages/offix-cache/src/utils/helperFunctions.ts
packages/offix-client/integration_test/karma.conf.js
packages/offix-client/integration_test/server/schema.js
packages/offix-client/integration_test/test/cache.test.js
packages/offix-client/integration_test/utils/graphql.queries.js

I found some unexpected behaviors when updating the cache using the `offlineMutation()` method that could be bugs so I have created a few integration tests to reproduce this behavior. 
My only doubt is if I'm using wrongly the library or there is actually one or more bugs.
This PR is meant to show the errors, and not to be merged. The fact that the tests are failing is wanted for now.

Add integration test for offlineMutation

---

examples/conflicts/package.json
lerna.json
packages/offix-cache/package.json
packages/offix-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json

fix: release v0.7.0

---

.github/CODEOWNERS

@wtrocki I left you as you did the same in the other repo. shout if you want to be removed.

fix: remove code owners

---

docs/ref-offline.md

Fixed typo on "online only". This directive can be only used on mutations.

Update on ref-online.md

---

packages/react-offix-hooks/.npmignore
packages/react-offix-hooks/README.md
packages/react-offix-hooks/package.json
packages/react-offix-hooks/src/OffixProvider.tsx
packages/react-offix-hooks/src/index.ts
packages/react-offix-hooks/src/useOfflineMutation.ts
packages/react-offix-hooks/src/utils.ts
packages/react-offix-hooks/tsconfig.json

feat: initial react-offix-hooks prototype

---

packages/offix-client/src/OfflineClient.ts
packages/offix-client/src/config/OffixDefaultConfig.ts

Without this actual extensibility is very limited

fix: Expose config in client

---

packages/react-offix-hooks/package.json

Upgrade dependency of offix-client to 0.8.1

Bump offix-client to 0.8.1

---

packages/offix-offline/src/offline/OfflineQueue.ts

typo: just an irrelevant typo

---

docs/ref-release-notes.md
packages/offix-client/src/OfflineClient.ts
packages/offix-client/src/cache.ts

Fix for https://github.com/aerogear/offix/issues/159

Expose persistor

---

examples/conflicts/package.json
lerna.json
packages/offix-cache/package.json
packages/offix-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/react-offix-hooks/package.json

chore: release 0.9.2-dev1

---

scripts/validateRelease.sh

ci: fix release validation script

---

docs/ref-offline.md
packages/offix-client/integration_test/test/cache.test.js
packages/offix-client/integration_test/test/conflict.test.js
packages/offix-client/integration_test/test/offline.test.js
packages/offix-client/src/OfflineClient.ts
packages/offix-client/src/apollo/ApolloOfflineClient.ts
packages/offix-offline/src/offline/OfflineError.ts
packages/react-offix-hooks/src/useOfflineMutation.ts

fix: deprecate offlineMutation in favour of offlineMutate

---

examples/conflicts/package.json
lerna.json
packages/offix-cache/package.json
packages/offix-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/react-offix-hooks/package.json

chore: release 0.9.2-dev2

---

packages/offix-client/src/OfflineClient.ts
packages/offix-client/src/apollo/ApolloOfflineClient.ts
packages/offix-client/src/apollo/ApolloOperationSerializer.ts
packages/offix-client/src/apollo/index.ts
packages/offix-client/src/apollo/optimisticResponseHelpers.ts
packages/offix-client/src/config/OffixClientConfig.ts
packages/offix-client/src/config/OffixDefaultConfig.ts
packages/offix-client/test/OfflineClient.api.test.ts

I have a dev release with these changes published. You can get it at with `npm install offix-client@next`

feat: apollo specific types for generics like OfflineQueue & OfflineStore

---

.github/CONTRIBUTING.md
README.md

- add link in main readme to contributing document
- tidy up commands in contributing document

add link in main readme to contributing document and tidy up commands in contributing document

---

packages/offix-offline/jest.config.js
packages/offix-offline/package.json
packages/offix-offline/test/IDProcessor.test.ts
packages/offix-offline/test/OfflineStore.test.ts

- clean up and make Offix offline tests work

Offix offline tests cleanup

---

docs/ref-offline.md
website/i18n/en.json
website/pages/en/index.js

* Adds a Github Button on the landing page. cc @wtrocki 
* Fixes some typos
* changes an id/generated url of the Offline Support page

doc: minor tweaks to docs site

---

README.md

Just adding badge for issue #204 
Just badge =D

doc: add Discord (chat) badge to README

---

docs/ref-release-notes.md

Prepares the release notes for our upcoming refactor release!

doc: update release notes

---

docs/ref-release-notes.md
packages/offix-client/src/OfflineClient.ts
packages/offix-client/src/config/OffixClientConfig.ts
packages/offix-client/src/config/OffixDefaultConfig.ts
packages/offix-client/test/OfflineClient.api.test.ts

feat: allow users to provide their own InMemoryCache

---

docs/getting-started.md

Add instructions to install offix from npm or yarn in the Getting Started section

docs: add install instructions for offix

---

README.md

This just simplifies the description and keeps it consistent with the website.

doc: update offix description in README.md

---

packages/offix-offline/src/conflicts/ConflictLink.ts

fix: check if exception is defined before proceed

---

docs/ref-react-offix-hooks.md
packages/react-offix-hooks/README.md
packages/react-offix-hooks/src/useOfflineMutation.ts
website/i18n/en.json
website/sidebars.json

This PR does the bare minimum to ensure the `react-offix-hooks` package will actually be somewhat usable in a project. Without these base level changes and docs in the website, there is no visibility and we will never get any usage/feedback.
Thankfully I did not need many changes and the docs were mostly written already.
See the screenshot to get an idea of what the new webpage looks like.

fix: react-offix-hooks fixes

---

docs/android.md
docs/ionic.md
docs/react-native.md
docs/ref-offix-scheduler.md
docs/ref-react-offix-hooks.md
website/i18n/en.json
website/sidebars.json

Adding very rough although highly needed information about our platform support.
This needs work howver it is good start to get offix docs into the right shape

fix: Platform docs

---

docs/getting-started.md
docs/ionic.md
docs/react-native.md
website/i18n/en.json
website/versioned_docs/version-0.11.0/android.md
website/versioned_docs/version-0.11.0/getting-started.md
website/versioned_docs/version-0.11.0/ionic.md
website/versioned_docs/version-0.11.0/react-native.md
website/versioned_docs/version-0.11.0/ref-react-offix-hooks.md
website/versioned_docs/version-0.11.0/ref-release-notes.md
website/versioned_sidebars/version-0.11.0-sidebars.json

doc: rebuild 0.11.0 docs

---

docs/ref-offline.md
packages/offix-client/src/apollo/conflicts/baseHelpers.ts
packages/offix-client/test/conflictBase.test.ts
packages/offix-client/test/mock/MockNetworkStatus.ts
packages/offix-client/test/mock/MockStore.ts
website/sidebars.json

fix: pass entire mutation options and typename to dataIdFromObject

---

docs/ref-configuration.md

fixes https://github.com/aerogear/offix/issues/302

fix: update docs links

---

docs/react-native.md

fixes https://github.com/aerogear/offix/issues/299

doc: add note about expo and async storage to docs

---

docs/ref-react-offix-hooks.md
packages/react-offix-hooks/src/useOfflineMutation.ts

breaking: refactor offline mutate

---

jest.config.js
package.json
packages/offix-cache/jest.config.js
packages/offix-client-boost/jest.config.js
packages/offix-client/jest.config.js
packages/offix-client/test/conflictBase.test.ts
packages/offix-conflicts-client/jest.config.js
packages/offix-conflicts-server/jest.config.js
packages/offix-offline/jest.config.js
packages/offix-scheduler/jest.config.js
packages/react-offix-hooks/jest.config.js

`npm run test` or `yarn test` for regular tests
`npm run coverage` or `yarn coverage` for code coverage

fix: test code coverage issues

---

.circleci/config.yml
.github/CONTRIBUTING.md
examples/react/index.html
examples/react/package.json
examples/server/docker-compose.yml
lerna.json
package.json

- Switched to workspaces
- Update circleci build script
- Update contributing guidelines
From root run the following commands:
`yarn`
`yarn build`

Switch to yarn workspaces

---

examples/react/package.json
packages/offix-cache/src/createMutationOptions.ts

The example app build was breaking on my end yesterday too, so I added the line back into the package.json that seems to fix things.

fix: react example app build issue

---

packages/offix-client-boost/integration_test/test/offline.test.js
packages/offix-client/integration_test/test/offline.test.js
packages/offix-client/src/ApolloOfflineClient.ts
packages/offix-client/src/apollo/optimisticResponseHelpers.ts
packages/offix-client/test/conflictBase.test.ts
packages/offix-client/test/optimisticResponseHelpers.test.ts
packages/offix-scheduler/src/queue/OfflineQueue.ts
packages/offix-scheduler/src/store/OfflineStore.ts
packages/offix-scheduler/test/OfflineStore.test.ts

fixes https://github.com/aerogear/offix/issues/374

fix: persist queue entries after updating optimistic ids

---

package.json

You can still bypass the precommit hook by using `git commit -n` if needed

fix: add precommit hook to run lint and test

---

examples/react-native/src/clientConfig.js
examples/react-native/src/components/Todo/TodoContent.js
examples/react-native/src/gql/queries.js
examples/react-native/src/helpers/ReactNativeNetworkStatus.js
examples/react/src/components/Todo/TodoContent.jsx
examples/react/src/gql/queries.js

- Fix React Native app network listener bug
- Fix delete query on both example apps

Example app bug fixes

---

packages/offix-cache/src/createOptimisticResponse.ts
packages/offix-cache/test/OptimisticResponse.test.ts

fix: id overwrite issue in optimistic responses

---

lerna.json
packages/offix-cache/package.json
packages/offix-client-boost/package.json
packages/offix-client/package.json
packages/offix-conflicts-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/offix-scheduler/package.json
packages/react-offix-hooks/package.json

chore: release 0.15.1

---

examples/react-native/package.json
examples/react-native/src/App.js
examples/react-native/src/clientConfig.js
examples/react-native/src/components/AddTodo.js

- Bump react version for react native sample to meet react-offix hooks peer dependency (this was causing an invalid hooks error)
- Fix issue with IP address for iOS simulator

React native fixes

---

website/versioned_docs/version-0.15.0/getting-started.md

Found some typos in the latest versioned docs while going through the website.

docs: fixed typos in docs

---

examples/react-native/src/App.js
examples/react-native/src/components/AddTodo.js
website/versioned_docs/version-0.15.0/ref-conflict-client.md

Just fixed some typos in the documentation

docs: fixed typos

---

website/src/components/Features/components/FeatureList.jsx
website/src/components/Features/components/styled.components.js
website/src/components/Features/styled.components.js
website/src/components/Hero/styled.components.js
website/src/components/Introduction/index.jsx
website/src/components/UI/Flex.jsx

Fix responsive issues with mobile version of docs landing page.

Docs responsive fixes

---

package.json

Trying to make any change in offix requires tests to pass. 
This is very very bad for general community that cannot create PR without failing tests. I know that works nice for maintainers but we should be focusing on community more than just ourselves.
See discussion on offix chat for more context

fix: remove precommit

---

lerna.json
packages/offix-cache/package.json
packages/offix-client-boost/package.json
packages/offix-client/package.json
packages/offix-conflicts-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/offix-scheduler/package.json
packages/react-offix-hooks/package.json

chore: release 0.15.2

---

lerna.json
packages/offix-cache/package.json
packages/offix-client-boost/package.json
packages/offix-client/package.json
packages/offix-conflicts-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/offix-scheduler/package.json
packages/react-offix-hooks/package.json

chore: release 0.15.3

---

lerna.json
packages/offix-cache/package.json
packages/offix-client-boost/package.json
packages/offix-client/package.json
packages/offix-conflicts-client/package.json
packages/offix-conflicts-server/package.json
packages/offix-offline/package.json
packages/offix-scheduler/package.json
packages/react-offix-hooks/package.json

chore: release 0.15.4

---

docs/ref-cache.md
packages/offix-cache/src/createMutationOptions.ts
packages/offix-cache/src/createSubscriptionOptions.ts

- Updated mutation and subscription cache helpers to provide support for field level cache updates.
- Updated documents to reflect new changes.

Cache pagination

---

examples/react/package.json
examples/react/src/clientConfig.js
examples/react/src/components/AddTodo.jsx
examples/react/src/gql/queries.js
examples/react/src/index.js
lerna.json

Removed file upload used for investigation.
All good here to be merged after verification

Update sample app

---

packages/offix-datastore/src/Model.ts

Quick event listener fix for DataStore

Fix event listener

---

packages/offix-client/src/apollo/optimisticResponseHelpers.ts
packages/offix-conflicts-client/src/index.ts
packages/offix-conflicts-client/src/state/LastUpdatedState.ts

Adding last updated state to be part of the supported states. 
No docs yet - need to think if we want to swap from versioned state etc. as default.

fix: add last updated state 

---

packages/offix-datastore/src/DataStore.ts
packages/offix-datastore/src/replication/GraphQLCrudQueryBuilder.ts
packages/offix-datastore/src/replication/GraphQLReplicator.ts
packages/offix-datastore/src/replication/ReplicationEngine.ts
packages/offix-datastore/src/replication/Replicator.ts
packages/offix-datastore/tests/DataStore.test.ts
packages/offix-datastore/tests/GraphQLReplication.test.ts
packages/offix-datastore/tests/Predicate.test.ts
packages/offix-datastore/tests/Replication.test.ts

Push Update and Delete operations to the server. Since update and delete are executed in batches, each affected row is pushed as a single operation to the server.

Push Update and Delete operations to server

---

docs/ref-datastore-getting-started.md
docs/ref-datastore-observing-changes.md
examples/react-datastore/src/datastoreConfig.js
examples/react-datastore/src/hooks.js
packages/offix-datastore/src/DataStore.ts
packages/offix-datastore/src/Model.ts
packages/offix-datastore/src/index.ts
packages/offix-datastore/src/replication/GraphQLReplicator.ts
packages/offix-datastore/src/replication/ReplicationEngine.ts
packages/offix-datastore/src/replication/Replicator.ts
packages/offix-datastore/src/replication/UrqlGraphQLClient.ts
packages/offix-datastore/src/storage/Storage.ts
packages/offix-datastore/tests/DataStore.test.ts
packages/offix-datastore/tests/GraphQLReplication.test.ts
packages/offix-datastore/tests/Replication.test.ts

- change `EventTypes` to be `DatabaseEvents` enum
- other quick fixes
- update docs
- update example

Use enums for events and other quick fixes

---

packages/offix-datastore/tests/__snapshots__/GraphQLReplication.test.ts.snap

fix: update snapshot

---

.circleci/config.yml
packages/offix-datastore/src/DataStore.ts
packages/offix-datastore/src/Model.ts
packages/offix-datastore/src/replication/GraphQLCrudQueryBuilder.ts
packages/offix-datastore/src/replication/GraphQLReplicator.ts
packages/offix-datastore/src/replication/Replicator.ts
packages/offix-datastore/src/storage/Storage.ts
packages/offix-datastore/src/utils/PushStream.ts
packages/offix-datastore/tests/DataStore.test.ts
packages/offix-datastore/tests/GraphQLReplication.test.ts
packages/offix-datastore/tests/Replication.test.ts
packages/offix-datastore/tests/__snapshots__/GraphQLReplication.test.ts.snap
packages/offix-datastore/tests/schema.json

This PR prepares us for MVP1. Here's what I've done here:
- I've changed the Model API so we can accept more configurations
- Given the Model objects access to a global replicator
- The previous two items allowed me to start delta synchronization in the Model object
- I stubbed out Subscriptions in the Model class
What we need to get delta synchronization working:
- we need a metadata store to hold lastSync for models
- we need a Predicate to GraphQLCrud filter converter
- we need to handle errors (technically the whole package needs this as there is no error handling yet) (Conflicts, etc.)

Receive changes from server

---

examples/react-datastore/package.json
examples/react-datastore/src/components/forms/AddTodo.tsx
examples/react-datastore/src/config/datastoreConfig.ts
examples/react-datastore/src/helpers/hooks.ts
examples/react-datastore/src/types.ts
packages/offix-datastore/package.json

Patching things up. Current api is to strongly typed and requires us to have 2 variations of typing for each operation.

fix: patch current types and add temporary id generation

---

packages/offix-datastore/package.json
packages/offix-datastore/src/Model.ts
packages/offix-datastore/src/replication/client/GraphQLClient.ts
packages/offix-datastore/src/replication/graphqlcrud/GraphQLCRUDReplicator.ts

Minor change to improve code readability, from this:
```
if (condition) 
throw new Error("message");
}
```
to this:
```
invariant(!condition, "message");
```

Tiny invariant

---

packages/offix-datastore/package.json
packages/offix-datastore/src/ModelSchema.ts
packages/offix-datastore/src/schema.ts

json schema layer

---

packages/offix-datasync-codegen/package.json

chore: bump cli

---

packages/offix-datastore/package.json

chore: bump datastore to 0.1.2

---

examples/react-datastore/src/App.tsx
examples/react-datastore/src/components/Todo/Todo.tsx
examples/react-datastore/src/components/forms/AddTodo.tsx
examples/react-datastore/src/components/forms/EditTodo.tsx
examples/react-datastore/src/components/forms/ToggleTodo.tsx
examples/react-datastore/src/datasync/config.ts
examples/react-datastore/src/helpers/hooks.ts
packages/offix-datastore/package.json
packages/offix-datastore/src/index.ts
packages/offix-datastore/src/react/ReducerUtils.ts
packages/offix-datastore/src/react/hooks/delete.ts
packages/offix-datastore/src/react/hooks/query.ts
packages/offix-datastore/src/react/hooks/save.ts
packages/offix-datastore/src/react/hooks/subscription.ts
packages/offix-datastore/src/react/hooks/update.ts
packages/offix-datastore/src/react/index.ts

This PR implements react hooks for offix-datasync. Some strategies for fetching and updating data will be implemented as soon as they are implemented in Models. The hooks are also integrated in the sample app. I haven't verified the hooks because verification with the linked local package is blocked by react. I recommend that the new changes be published before the hooks can be used.

React hooks

---

examples/react-datastore/src/components/Todo/TodoList.tsx
packages/datastore/datastore/src/storage/adapters/WebSQLAdapter.ts
packages/datastore/datastore/tests/SQLite.test.ts
packages/datastore/datastore/tests/schema.json

Just a small refactor. This now works in the sample app (except for the update method).
To verify add the following to the `datastore` config in the `datasync/config.ts` file:
```
export const datastore = new DataStore({
...
}, {
storeAdapter: new WebSQLAdapter("offixdb", 2)
});
```

Sqlite refactor

---

examples/react-datastore/src/components/Todo/Todo.tsx
examples/react-datastore/src/components/forms/EditTodo.tsx
examples/react-datastore/src/components/forms/ToggleTodo.tsx
examples/react-datastore/src/helpers/hooks.ts
packages/datastore/datastore/src/index.ts
packages/datastore/datastore/src/storage/adapters/indexedDB/IndexedDBStorageAdapter.ts

Fixed failing test and updated the sample app to use new filters

Quick fixes and sample app integration

---

packages/datastore/datastore/src/storage/adapters/websql/WebSQLAdapter.ts
packages/datastore/datastore/src/storage/adapters/websql/filterToSQL.ts
packages/datastore/datastore/src/storage/adapters/websql/utils.ts
packages/datastore/datastore/src/storage/index.ts
packages/datastore/datastore/tests/Filters.test.ts
packages/datastore/datastore/tests/SQLite.test.ts

Implemented a converter for filters to SQL expressions. Tests are include for verification,

Filter to sql

---

packages/datastore/datastore/src/Model.ts
packages/datastore/datastore/src/storage/LocalStorage.ts
packages/datastore/datastore/src/storage/adapters/indexedDB/IndexedDBStorageAdapter.ts
packages/datastore/datastore/src/storage/adapters/websql/WebSQLAdapter.ts
packages/datastore/datastore/src/storage/api/StorageAdapter.ts
packages/datastore/datastore/tests/DataStore.test.ts

Implementation of `saveOrUpdate` for both IDB and WebSQL

Datastore save or update

---

examples/react-datastore/package.json
packages/datastore/datastore/src/DataStore.ts
packages/datastore/datastore/src/replication/GraphQLReplicator.ts
packages/datastore/datastore/src/replication/api/MetadataModels.ts
packages/datastore/datastore/src/replication/mutations/MutationsQueue.ts
packages/datastore/datastore/src/replication/queries/DeltaReplicator.ts
packages/datastore/datastore/src/replication/subscriptions/SubscriptionReplicator.ts

Fixing issues with stores etc.
As draft as more issues appear after resolving current ones

Fix master app

---

packages/datastore/datastore/src/react/hooks/query.ts

I implemented the work discussed here #730. I have tested this with sample app.

Update query hooks to support queryById

---

docs/datastore/cli.md
docs/datastore/edits.md
docs/datastore/introduction.md
docs/datastore/queries.md
docs/datastore/react.md
docs/datastore/ref-getting-started.md
docs/datastore/subscriptions.md

- Minor changes to the docs
- I changed the lists on the query page to 2 tables (that could possibly be styled better)

Datastore docs update

---

docs/offix/ref-advanced.md
website/docusaurus.config.js
website/versioned_docs/version-0.13.0/ref-advanced.md
website/versioned_docs/version-0.14.0/ref-advanced.md
website/versioned_docs/version-0.15.0/ref-advanced.md

@wtrocki had to fix some broken links for the deploy.

docs: fix broken links

---

packages/datastore/datastore/src/ModelSchema.ts

I have just gone in and added comments to the ModelSchema for future reference.

Add comments to model schema (fixes #740)

---

docs/datastore/cli.md
packages/datastore/cli/package.json
packages/datastore/cli/src/generate.ts
packages/datastore/cli/src/index.ts
packages/datastore/cli/src/utils.ts
packages/datastore/cli/tests/Cli.test.ts
packages/datastore/cli/tests/__snapshots__/Cli.test.ts.snap

What I have done here;
- Added default values for parameters
- Switched to positional arguments
- Allow directory to be specified in schema argument
- CLI Tests have been included for all changes

Cli command improvements

---

docs/datastore/react-native.md
website/sidebars.json

Docs for React Native storage and network info integration

React Native Integration - Docs

---

packages/datastore/datastore/src/replication/mutations/MutationsQueue.ts
packages/datastore/datastore/src/replication/mutations/QueueUpdateProcessor.ts
packages/datastore/datastore/tests/MutationQueue.test.ts

This turned out to be much harder than expected. I'm still testing this with sample app and working out bugs.

Swap client ids in queue

---

docs/datastore/introduction.md
packages/datastore/datastore/tests/MutationQueue.test.ts

- Cleared TODO in datastore docs introduction page and
- Removed test restriction in MutationQueue.test.ts

Quick docs and test fix

---

examples/react-datastore/.gitignore
examples/react-datastore/README.md
examples/react-datastore/capacitor.config.json
examples/react-datastore/package.json
packages/datastore/cli/src/OffixDataStoreConfig.ts
packages/datastore/cli/src/OffixDataStorePlugin.ts
packages/datastore/cli/src/OffixDataStorePluginValidator.ts
packages/datastore/cli/src/generate.ts
packages/datastore/cli/src/index.ts
packages/datastore/datastore/src/ModelSchema.ts
packages/datastore/datastore/src/utils/logger.ts

I've added the basic config for the capacitor app, you'll just need to the path to your android studio in the config file

Add capacitor config to sample app

---

packages/datastore/cli/src/generate-documents/createJsonSchema.ts
packages/datastore/cli/src/generate.ts
packages/datastore/cli/tests/createJsonSchema.test.ts

I wanted to verify this so wrote a test which I think should pass but isn't. I don't have all the context so I could be wrong here. Take a look and see if this is expected or unexpected behaviour.

test: add test to check if manyToOne relationship is added

---

packages/offix/cache/package.json
packages/offix/client-boost/integration_test/package.json
packages/offix/client-boost/package.json
packages/offix/client/package.json
packages/offix/conflicts-client/package.json
packages/offix/conflicts-server/package.json
packages/offix/offline/package.json
packages/offix/react-hooks/package.json
packages/offix/scheduler/package.json

chore: bump versions for release

---

website/versioned_docs/version-0.15.0/getting-started.md

Quick fix for a small typo found in docs.

fix: realated -> related
