packages/offix-client/src/OfflineApolloClient.ts, packages/offix-client/src/OfflineClient.ts, packages/offix-client/src/config/DataSyncConfig.ts, packages/offix-client/src/index.ts, packages/offix-client/src/offline/OfflineMutationsHandler.ts, packages/offix-client/src/offline/OfflineQueue.ts, packages/offix-client/src/offline/events/CompositeQueueListener.ts, packages/offix-client/src/offline/events/ListenerProvider.ts, packages/offix-client/src/offline/events/OfflineQueueListener.ts, packages/offix-client/src/offline/index.ts, packages/offix-client/test/OfflineClientTest.ts
Allow registering multiple listeners for detecting offline queue changes like an item added etc. Additionally, we will be enabling registering listeners on the fly as opposed to the one single startup listener
=> Enable pluggable listeners for offline changes

packages/offix-client/package.json, packages/offix-client/src/cache/createMutationOptions.ts, packages/offix-client/src/cache/createSubscriptionOptions.ts, packages/offix-client/test/CacheHelpersTest.ts, packages/offix-client/test/mock/mutations.ts
This PR provides the ability to update multiple queries in the cache when a mutation is run.
It also exports valuable functions the client may want to use without using the full cache helper function.
=> feat: support multiple queries, export functions

packages/offix-cache/src/cache/mutations.ts
Currently returnType is optional but we always try to build an optimistic response regardless of whether or not it is provided. We should not build one if we don't get a returnType.
=> Fix to not create optimistic response when no returnType is passed

.circleci/config.yml, README.md, docs/README.md, docs/getting-started.md, docs/ref-release-notes.md, packages/offix-client/package.json, packages/offix-client/src/OfflineClient.ts, packages/offix-client/src/cache.ts, packages/offix-client/src/config/OffixClientConfig.ts, packages/offix-client/src/config/OffixDefaultConfig.ts, packages/offix-client/src/config/index.ts, packages/offix-client/src/links/AuthLink.ts, packages/offix-client/src/links/LinksBuilder.ts, packages/offix-client/src/links/WebsocketLink.ts, packages/offix-client/src/utils/platform.ts, packages/offix-client/test/OffixConfigTest.ts, packages/offix-client/test/SyncConfigTest.ts, packages/offix-offline/package.json, packages/offix-offline/src/conflicts/ConflictLink.ts, packages/offix-offline/src/conflicts/strategies/strategies.ts, packages/offix-offline/test/ConflictHandlerTest.ts
I went thru the code and removed bad smells and other problems that were related with using legacy api or bad naming. There are no controversial changes.
- UseClient was documented in docs but we exposed clientWins - clientWins is different approach than UseClient so this required rename.
- Renamed DataSyncConfig 
- Removed mobile core dependency that brings up 300kb into a bundle (sick!) 
- Renamed folders for circleci builds
- Removed old legacy references to our fork of cache persist.
=> General improvements

packages/offix-client/integration_test/test/offline.test.js
The part of integration test for mutationCacheUpdates should check that cache was updated after client restarts. The tests passes now, but should actually do the check with `cache-first` query.
=> mutationCacheUpdates integration test fix

packages/offix-cache/src/cache/mutations.ts, packages/offix-client/integration_test/test/offline.test.js, packages/offix-offline/src/conflicts/BaseLink.ts, packages/offix-offline/src/offline/OperationQueueEntry.ts, packages/offix-offline/src/offline/processors/IDProcessor.ts
this commit fixes a problem where we assume id is the unique
field for an object. to fix this i have used the idField which
we already have available. if it is not provided in context then
we revert to the default of "id"
=> fix: stop using hardcoded id field for operations.

packages/offix-client/src/auth/AuthContextProvider.ts, packages/offix-client/src/links/AuthLink.ts, packages/offix-client/src/links/WebsocketLink.ts
Before this change, the function was returning an object of the type `{ Authorization: any }`, which is incompatible with what is expected from `connectionParams`. This change uses the same methods as they are used on AuthLink.
Tests are not passing but it seems to be unrelated to this change (errors come from `CacheHelpersTest.ts`)
=> Make WebsocketLink headers work the same as AuthLink

docs/ref-release-notes.md, packages/offix-client/integration_test/test/cache.test.js, packages/offix-client/src/OfflineClient.ts, packages/offix-offline/src/offline/OfflineMutationsHandler.ts
Global cache updates are required now to see optimistic response on every offline mutation. This change will allow us to use context attached cache update. 
Documentation is still valid, this will be just a major usability feature that will let us to experiment with sample apps without unexpected behavior.
=> Do not require cache updates without app restart

packages/offix-client/integration_test/test/cache.test.js, packages/offix-offline/src/offline/OfflineError.ts, packages/offix-offline/src/offline/OfflineMutationsHandler.ts
What I discovered is this issue:
```
client.mutate(...).catch((error)=> {
if(error.networkError && error.networkError.offline){
const offlineError =  error.networkError;
offlineError.watchOfflineChange().then((result) => {
console.log(result) // result is always undefined
})
}
});
```
Working on a test now.
=> fix: ensure mutation result is returned from watchOfflineChange

packages/offix-offline/src/offline/OfflineLink.ts
When adding items to the offline queue we currently do nothing if an error occurs. This can happen for a number of reasons. One being if the storage is not ready or if the cache quota is exceeded.
=> fix: catch errors when adding to offline queue

docs/ref-release-notes.md, packages/offix-client/src/OfflineClient.ts, packages/offix-client/test/OfflineClientTest.ts
Make the apollo client accessible on the OfflineClient class. This drastically simplifies how the client can be accessed within different contexts across applications.
=> feat: make OfflineClient.apolloClient public

packages/offix-client/src/OfflineClient.ts, packages/offix-client/src/config/OffixClientConfig.ts, packages/offix-client/src/links/LinksBuilder.ts
We have implemented Offix to our chat-app and problem we have is that Offix does not support credentials in http links. Below are our initial proposed changes. Let us know what do you think!
=> feat: add httpOptions to init()

packages/offix-offline/src/offline/OfflineMutationsHandler.ts
OfflineMutationsHandler will deal with two types of elements:
- Elements enqueued instantly after scheduling
- Element enqueued after restart
Second option is missing function calls and we should always check if they exist.
1. Go offline
2. Add some tasks
3. Restart website when online 
4. See no error from #145
=> Check if dealing with JSON or Operation object in persistent queue

packages/offix-client/integration_test/test/cache.test.js, packages/offix-offline/src/conflicts/handler/ConflictHandler.ts, packages/offix-offline/src/conflicts/strategies/strategies.ts, packages/offix-offline/src/utils/cacheHelper.ts
we need to use the parent optimistic data when available as this is most
likely what the user will be looking at when interacting with an object.
also, the client should be added to the resolve function for the case
where client diff is empty because of an optimistic response.
=> fix: use optimistic data if available. add client to resolve.

packages/offix-conflicts-server/jest.config.js, packages/offix-conflicts-server/package.json, packages/offix-conflicts-server/test/HashObjectState.test.ts, packages/offix-conflicts-server/test/VersionedObjectState.test.ts
- migrate tests for offix-conflicts-server from ava to jest
=> migrate tests for offix-conflicts-server from ava to jest

docs/ref-configuration.md, docs/ref-offline.md, packages/offix-client/src/ApolloOfflineClient.ts, packages/offix-client/src/config/ApolloOfflineClientConfig.ts, packages/offix-client/src/config/ApolloOfflineClientOptions.ts, packages/offix-client/test/OfflineClient.api.test.ts
Allows the developer to pass their own `CachePersistor` object. This would close both https://github.com/aerogear/offix/issues/281 and https://github.com/aerogear/offix/issues/273
It can be done as follows:
```js
import { ApolloOfflineClient, createDefaultCacheStorage } from "offix-client";
import { HttpLink } from "apollo-link-http";
import { InMemoryCache } from "apollo-cache-inmemory";
import { CachePersistor } from "apollo-cache-persist";
const link = new HttpLink({ uri: "http://example.com/graphql" });
const cache = new InMemoryCache()
const cachePersistor = new CachePersistor({
cache,
storage: createDefaultCacheStorage()
})
const client = new ApolloOfflineClient({
cache,
cachePersistor,
link
});
```
One thing to note, now that users can pass their own cachePersistor object. Do we …
=> Presistor options

packages/offix-client/package.json, packages/offix-client/src/ApolloOfflineClient.ts, packages/offix-client/src/cache.ts, packages/offix-scheduler/package.json, packages/offix-scheduler/src/OffixScheduler.ts, packages/offix-scheduler/src/index.ts, packages/offix-scheduler/src/queue/OfflineQueue.ts, packages/offix-scheduler/src/store/IDBLocalStore.ts, packages/offix-scheduler/src/store/OfflineStore.ts, packages/offix-scheduler/src/store/defaultStorage.ts, packages/offix-scheduler/src/store/index.ts, packages/offix-scheduler/test/IDBLocalStore.test.ts, packages/offix-scheduler/test/OffixNoIDB.test.ts, packages/offix-scheduler/test/OfflineStore.test.ts
- Implemented error handling for when indexedDB not available (e.g. Firefox private mode), preventing the app from crashing
- Removed idb-localstorage dependency and added the class directly to offix-scheduler as IDBLocalStore
- Added tess for offix when indexedDB not available and added tests for IDBLocalStore
=> fix: error handling for when indexedDB not available

.circleci/config.yml
Motivation 
CircleCI has quota now and doing npm updates everytime is hitting the limits that npmjs put in. Recommendation from the circleci is to remove this update as it is mostly redundant and slow down the build
=> chore: Remove npm update from circleci

tsconfig.json
Source maps are not working and pointing to the wrong locations in ts files because of chunks for both dev and production. We need to remove them and base our debug sessions on js files which is even more easier for released packages
=> chore: Stop generating source maps

packages/offix-client-boost/integration_test/utils/network.js, packages/offix-client/integration_test/utils/network.js, packages/offix-client/test/mock/MockNetworkStatus.ts, packages/offix-offline/src/network/CordovaNetworkStatus.ts, packages/offix-offline/src/network/NetworkStatus.ts, packages/offix-offline/src/network/WebNetworkStatus.ts, packages/offix-offline/test/mock/NetworkState.ts, packages/offix-scheduler/src/OffixScheduler.ts, packages/offix-scheduler/test/mock/ToggleableNetworkStatus.ts, packages/react-offix-hooks/src/useNetworkStatus.ts, packages/react-offix-hooks/test/mock/MockNetworkStatus.ts, packages/react-offix-hooks/test/useNetworkStatus.test.tsx
Currently event listeners are added to the `WebNetworkStatus` and `CordovaNetworkStatus` classes. The issue with this is that it offers no flexibility, and we keep adding listeners without the ability for removing them at a later stage. 
For now the proposed changes are only slightly breaking, as the api has been kept the same. However, instead of a new event listener being added every time, the event listeners are created on instantiated and added to the window that trigger a `handleNetworkStatusChange` method. The responsibility of this method is to loop through the array of listeners and apply the result of the status change.
Code example: 
```
const listener = {
onStatusChange(networkInfo: NetworkInfo) {
self.online = networkInfo.online;
if (self.online) {
queue.forwardOperations();
} …
```
=> breaking: refactor network status interface

.vscode/launch.json, docs/ref-configuration.md, package.json, packages/offix-cache/package.json, packages/offix-cache/src/createMutationOptions.ts, packages/offix-cache/src/createOptimisticResponse.ts, packages/offix-cache/src/utils/helperFunctions.ts, packages/offix-cache/test/OptimisticResponse.test.ts, packages/offix-client/integration_test/karma.conf.js, packages/offix-client/package.json, packages/offix-client/src/ApolloOfflineClient.ts, packages/offix-client/src/apollo/LinksBuilder.ts, packages/offix-client/src/apollo/conflicts/ConflictLink.ts, packages/offix-client/src/apollo/conflicts/baseHelpers.ts, packages/offix-client/src/apollo/optimisticResponseHelpers.ts, packages/offix-client/src/config/ApolloOfflineClientConfig.ts, packages/offix-client/src/config/ApolloOfflineClientOptions.ts, packages/offix-client/src/index.ts, packages/offix-client/src/utils/objectUtils.ts, packages/offix-client/test/optimisticResponseHelpers.test.ts, packages/offix-client/traversetest.js
I've brought in a new dependency in order to solve these issues. [traverse](https://github.com/substack/js-traverse/blob/master/index.js) is a ~300 line dependency.
* `createOptimisticResponse` flattens `variables` this means no need for a mapper function. If this flattening does not work, then use `createOptimisticResponse` directly passing in the correct variables, or supply your own object.
* `replaceClientGeneratedIdsInQueue` is able to deep replace optimistic id values in queue entries no matter the location. This solves issues where `variables` isn't a flat object. (e.g. using `input` types). It also solves issues where entries in the queue reference other optimistically created objects. i.e. https://github.com/aerogear/offix/issues/367
Check unit tests for examples
=> fix: improve queue handling of optimistic ids + InputMapper

docs/ref-conflict-client.md, packages/offix-client/integration_test/test/conflict.test.js, packages/offix-client/src/ApolloOfflineClient.ts, packages/offix-client/src/apollo/conflicts/CompositeConflictListener.ts, packages/offix-client/src/apollo/index.ts, packages/offix-client/src/config/ApolloOfflineClientConfig.ts
Adds a `CompositeConflictListener` class that always gets passed down to the `ConflictLink`. This allows us to add/remove listeners as needed. It's quick and dirty but it works and it has an integration test.
=> feat: allow for adding conflict listeners after client creation

packages/offix-cache/src/createMutationOptions.ts, packages/offix-cache/src/index.ts
Add ability to provide cache updates for the pagination/deltasync
=> Pagination container cache updates.

packages/offix-datastore/src/utils/PushStream.ts, packages/offix-datastore/tests/DataStore.test.ts
Previous subscribers to Storage stream are overwritten when a new one is added. I have added a fix that collects all observers in an array which solves the problem. I update the "Observe local store for changes" test in `DataStore.test.ts` to include two subscriptions to verify that the fix works.
=> Fix problem with multiple subscribers

packages/offix-client/src/apollo/optimisticResponseHelpers.ts
Even driven engine messes things up - it tries to restore changes that replication already removed. 
This fix patches the problem to avoid breaking client. However entire event driven locking need to be done - in separate PR
=> fix: allow to use offline change without optimistic response

packages/offix-datastore/src/replication/GraphQLCrudQueryBuilder.ts, packages/offix-datastore/src/replication/GraphQLReplicator.ts, packages/offix-datastore/tests/__snapshots__/GraphQLReplication.test.ts.snap
Adding first part of the work that will add graphqlcrud queries. 
There is problem with probability - names are not deterministic. 
We need to resolve that separately and possibly using single tooling to generate static resources. 
Going to continue work on this to explore how we fetch data first and then focus on edits.
=> fix: add graphql-crud compatible queries

docs/ref-datastore-manipulating-data.md, packages/offix-datastore/src/DataStore.ts, packages/offix-datastore/src/Model.ts, packages/offix-datastore/src/predicates/Operators.ts, packages/offix-datastore/src/predicates/Predicates.ts, packages/offix-datastore/src/replication/GraphQLCrudQueryBuilder.ts, packages/offix-datastore/src/storage/Storage.ts, packages/offix-datastore/src/storage/adapters/IndexedDBStorage.ts, packages/offix-datastore/src/storage/adapters/defaultStorage.ts
Implemented all the operators used in [GraphQLCrud filters](https://graphqlcrud.org/docs/next/find/#filtering). I modified Predicates such that the type of a field determines the allowed operators for that field. For example, numbers cannot use the "startsWith" operator. Also, only values of the same type or type[] can be compared. For example, you can perform the greater than operation on two numbers, not a number and a string.
=> Typesafe and complete operators closes #580

docs/ref-configuration.md
The URL to AuthContext in the description of the `authContextProvider` option for the offix-client-boost createClient function has a typo.
=> Fix broken link in ref-configuration.md

packages/offix-datastore/src/Model.ts, packages/offix-datastore/src/predicates/Operators.ts, packages/offix-datastore/src/predicates/PredicateFunctions.ts, packages/offix-datastore/src/replication/api/GraphQLClient.ts, packages/offix-datastore/src/replication/api/Replicator.ts, packages/offix-datastore/src/replication/client/UrqlGraphQLClient.ts, packages/offix-datastore/src/replication/graphqlcrud/GraphQLCRUDReplicator.ts, packages/offix-datastore/tests/GraphQLReplication.test.ts, packages/offix-datastore/tests/Replication.test.ts
To enable predicate to filter conversion, I:
- modified Filter Operators and Expression Operators to include their op name not just the function
- the op name of these Operators are used in the graphql crud layer to create graphql crud compatible filters
To verify the predicate to filter conversion, simply run tests. I added a describe block with "predicate to filter" tests to GraphQLReplication tests
=> Predicate filter conversion

examples/react-datastore/src/App.tsx, examples/react-datastore/src/helpers/hooks.ts, packages/offix-datastore/src/DataStore.ts, packages/offix-datastore/src/replication/client/GraphQLClient.ts, packages/offix-datastore/src/utils/NetworkStatus.ts, packages/offix-datastore/tests/DataStore.test.ts
I have created a network status interface that uses the websocket connection as an indication of whether the client is online or offline. There are still a few todos and things that need to be added once the replication pr is merged (https://github.com/aerogear/offix/pull/617)
=> Clientstore network

packages/offix-datastore/src/Model.ts
Very quick fix for metadata saved without name
=> fix metadata saved without model name

examples/react-datastore/src/datasync/config.ts, packages/offix-datastore/src/DataStore.ts, packages/offix-datastore/src/Model.ts, packages/offix-datastore/src/replication/GraphQLReplicator.ts, packages/offix-datastore/src/replication/ModelReplication.ts, packages/offix-datastore/src/replication/api/Replicator.ts, packages/offix-datastore/src/replication/mutations/MutationsQueue.ts, packages/offix-datastore/src/storage/LocalStorage.ts, packages/offix-datastore/tests/Storage.test.ts, packages/offix-datasync-codegen/src/OffixDataSyncPlugin.ts, packages/offix-datasync-codegen/tests/__snapshots__/DataSyncClientPlugin.test.ts.snap
In this PR, I have moved events to Model. We need to implement update strategies so replication is no longer event-based. Now we can fire events after replication or before replication. We need to rethink the information in change events since replication no longer uses events. I didn't change the code too much, there are still lots of improvements we can make now that replication is called in Model.
=> Move events to model

examples/react-datastore/src/App.tsx, packages/datastore/datastore/package.json, packages/datastore/datastore/src/react/hooks/query.ts, packages/datastore/datastore/src/storage/adapters/indexedDB/IndexedDBStorageAdapter.ts, packages/datastore/datastore/src/storage/adapters/indexedDB/Predicate.ts, packages/datastore/datastore/src/storage/adapters/websql/WebSQLAdapter.ts, packages/datastore/datastore/src/storage/adapters/websql/filterToSQL.ts, packages/datastore/datastore/src/storage/adapters/websql/utils.ts, packages/datastore/datastore/src/utils/PushStream.ts, packages/datastore/datastore/tests/Filters.test.ts
I modified the sample app to handle change events. I also tried to verify that the `contains` op works when using websql. It works for strings but not for arrays (I created test cases for both). I created an issue detailing the problem with arrays on websql #712. Getting the sample to work with the linked package was tricky but you can run it if you go into `offix/node_modules` and delete the react folder. Note that "react" will be re-installed the next time you run `yarn install` inside the workspace whether there's a react dependency in datastore or not because "react-offix-hooks" depends on it too. I also removed the react dependency but had to add it again because "urql" requires it and the tests won't run. Other small fixes are also in this PR.
I have added cursor support for …
=> Quick fixes and IDB Cursor Support

packages/datastore/datastore/src/Model.ts, packages/datastore/datastore/src/storage/LocalStorage.ts, packages/datastore/datastore/src/storage/adapters/indexedDB/IndexedDBStorageAdapter.ts, packages/datastore/datastore/src/storage/adapters/utils.ts, packages/datastore/datastore/src/storage/adapters/websql/WebSQLAdapter.ts, packages/datastore/datastore/src/storage/api/StorageAdapter.ts, packages/datastore/datastore/tests/DataStore.test.ts
Implementation of Query, Update and Delete by ID. Here, I added three new methods to our API that performs, query, update and delete operations using the ID. Although the methods have "ById" in their names, I do not use "Hardcoded id", I obtain the primary key from the store schema and use it for the operations. It might be better for us to by Primary Key(like updateByPrimaryKey) instead since we are not actually using "id".
=> Query, Update and Delete by ID

docs/datastore/react.md, docs/datastore/subscriptions.md, examples/react-datastore/src/App.tsx, packages/datastore/datastore/package.json, packages/datastore/datastore/src/Model.ts, packages/datastore/datastore/src/react/hooks/query.ts, packages/datastore/datastore/src/react/hooks/subscription.ts, packages/datastore/datastore/tests/DataStore.test.ts, packages/datastore/datastore/tests/React.test.ts
Here, I have implemented the new `subscribeToMore` API discussed in #767. I had to expose the Model schema through a `getSchema` method so I could obtain primaryKey for use in state update functions. I also modified `Model.subscribe` to accept an array of events to watch.
=> New subscribe to more api

packages/datastore/datastore/src/react/hooks/update.ts
This fixes loop on hook. Hook is called in loop because of data state changes (however strange thing happens when only id is present. This seems to solve issue. There might be more elegant solution though
#875
=> fix: Loop on hooks

docs/datastore/react.md, docs/offix/ref-cache.md, examples/react-datastore/src/App.tsx, examples/react-native/src/App.js, examples/react-native/src/components/TodoList.js, examples/react/src/App.tsx, examples/react/src/types.ts, packages/datastore/datastore/src/react/ReducerUtils.ts, packages/datastore/datastore/src/react/hooks/delete.ts, packages/datastore/datastore/src/react/hooks/query.ts, packages/datastore/datastore/src/react/hooks/save.ts, packages/datastore/datastore/src/react/hooks/update.ts, packages/offix/cache/src/api/CacheUpdates.ts, packages/offix/cache/src/createSubscriptionOptions.ts
This pull request renames variables and updates in offix-datastore and updates the documentation to comply with the changes.
* Renamed `isLoading` to `loading`
* Renamed `subscribeToMore` to `subscribeToUpdates`
* Updated docs to reflect the changes
=> Rename variables and functions in offix-datastore

packages/offix/client/src/index.ts
Fix for #896 
Hi! I'm new to offix development so thought it would be best to start with this small PR. From what I understood `ApolloQueryResult` needed to be exported from offix client in order to get rid of any direct dependencies to `apollo-client`. Please let me know in case something else also needs to be exported. Thanks.
=> chore(offix-client): exported ApolloQueryResult

packages/datastore/datastore/tests/DataStore.test.ts, packages/offix/client/test/mock/MockStore.ts
These are the errors due to which the checks are failing for PR #757:
```python
FAIL  packages/offix/client/test/conflictBase.test.ts
● Test suite failed to run
packages/offix/client/test/mock/MockStore.ts:16:7 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
16       resolve();
~~~~~~~~~
node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
~~~~~~~~~~~~~~~~~~~~~~~~~
An argument for 'value' was not provided.
packages/offix/client/test/mock/MockStore.ts:23:7 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
23       resolve(); …
```
=> fix(deps): fix failing dependency bumps

packages/offix/conflicts-client/src/handler/ConflictHandler.ts, packages/offix/conflicts-client/test/ConflictHandler.test.ts
The conflict handler failed to detect conflict when null attribute are present
The correction test `typeof(base[key])` object's attribute to check the existence of the attribute on object instead of just check `base[key]`
=> fix(conflictHandler): type check on object attribute to allow null value

examples/react-datastore/package.json, examples/react-datastore/src/App.tsx, examples/react-datastore/src/components/forms/EditTodo.tsx, examples/react-datastore/src/components/forms/ToggleTodo.tsx, packages/datastore/datastore/package.json, packages/datastore/datastore/src/replication/GraphQLReplicator.ts, packages/datastore/datastore/src/replication/mutations/MutationsQueue.ts, website/sidebars.json
- This is PR restores a basic id swap. It will remove the object with the client ID from the store
- This won't replace items in the mutation queue that have the client id
- The mutation queue was missing the ability to stop and restart the queue processor
- Added manual stop and stop for replication in the example app
=> Basic datastore id swap

examples/react-datastore/package.json, examples/react-datastore/src/App.tsx, packages/datastore/datastore/package.json, packages/datastore/datastore/src/DataStore.ts, packages/datastore/datastore/src/replication/GraphQLReplicator.ts, packages/datastore/datastore/src/replication/fetch/FetchReplicator.ts
- Provide the ability to subscribe to datastore network status changes.
=> Datastore network indicator (fixes #1069)
